name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build Thor
        run: dotnet publish Thor.sln -c Release -r win-x64
      - uses: actions/upload-artifact@v4
        with:
          name: Thor-Windows.exe
          path: TheAirBlow.Thor.Shell/bin/Release/net9.0/win-x64/publish/Thor.exe
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build Thor
        run: dotnet publish Thor.sln -c Release -r linux-x64
      - uses: actions/upload-artifact@v4
        with:
          name: Thor-Linux
          path: TheAirBlow.Thor.Shell/bin/Release/net9.0/linux-x64/publish/Thor
  build-macos:
    name: MacOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build Thor
        run: dotnet publish Thor.sln -c Release -r osx-x64
      - uses: actions/upload-artifact@v4
        with:
          name: Thor-MacOS
          path: TheAirBlow.Thor.Shell/bin/Release/net9.0/osx-x64/publish/Thor